"""
Praheri.AI Backend — Application Entrypoint

This is a genuine, runnable FastAPI application. It currently exposes a
health-check endpoint and a stub route group for the agent pipeline.

What works right now:
    - The app boots and serves requests.
    - The /health endpoint returns a real status response.
    - The route structure for investors/alerts/agents/compliance/audit is
      defined so the API contract is stable for frontend development,
      even though the underlying handlers are not yet wired to the
      database or to the Sentinel/Skeptic/Guardian agents.

What is NOT implemented yet (tracked in GitHub Issues, Milestones M1-M4):
    - Database connectivity (SQLAlchemy session, models)
    - Sentinel/Skeptic agent calls to the Claude API
    - Guardian Agent deterministic policy evaluation
    - Persistence of agent decisions and audit logs

Each stub route below raises HTTPException(501) explicitly rather than
returning fake data, so the API never silently lies about its own state.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from datetime import datetime, timezone

app = FastAPI(
    title="Praheri.AI API",
    description="Autonomous investor protection agent — backend service",
    version="0.1.0-phase1-prototype",
)

# CORS is open for local development only. Restrict this list before any
# real deployment beyond a local/demo environment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class HealthResponse(BaseModel):
    status: str
    timestamp: str
    version: str


@app.get("/health", response_model=HealthResponse, tags=["system"])
async def health_check() -> HealthResponse:
    """Real, working health check — confirms the service is up."""
    return HealthResponse(
        status="ok",
        timestamp=datetime.now(timezone.utc).isoformat(),
        version=app.version,
    )


@app.get("/api/v1/investors/{investor_id}", tags=["investors"])
async def get_investor(investor_id: str):
    """
    Planned: retrieve an investor profile from the database.
    Not yet implemented — depends on Milestone M1 (data layer).
    """
    raise HTTPException(
        status_code=501,
        detail=(
            "Not implemented yet. This endpoint will return the investor "
            "profile once the database layer (Milestone M1) is built. "
            "See GitHub Issues for current status."
        ),
    )


@app.get("/api/v1/investors/{investor_id}/alerts", tags=["alerts"])
async def get_investor_alerts(investor_id: str):
    """
    Planned: return active agent-generated alerts for an investor.
    Depends on the full Sentinel -> Skeptic -> Guardian pipeline
    (Milestones M2-M4) being implemented and persisted.
    """
    raise HTTPException(
        status_code=501,
        detail=(
            "Not implemented yet. Alerts are generated by the agent "
            "pipeline, which is scoped for Milestones M2-M4."
        ),
    )


@app.post("/api/v1/agents/sentinel/evaluate", tags=["agents"])
async def trigger_sentinel_evaluation(investor_id: str):
    """
    Planned: trigger the Sentinel Agent to evaluate an investor's recent
    behavior against their baseline and propose an action if warranted.
    Not implemented — see app/agents/sentinel.py (Milestone M2).
    """
    raise HTTPException(
        status_code=501,
        detail="Sentinel Agent integration is planned for Milestone M2.",
    )


@app.get("/api/v1/compliance/queue", tags=["compliance"])
async def get_compliance_queue():
    """
    Planned: return the prioritized escalation queue for compliance
    officers, populated only by Guardian-Agent-routed cases.
    Not implemented — depends on Milestone M4 (Guardian Agent) and
    Milestone M6 (compliance console backend support).
    """
    raise HTTPException(
        status_code=501,
        detail="Compliance queue depends on the Guardian Agent (Milestone M4).",
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
